Compute
chaostoolkit-incubator/chaostoolkit-google-cloud-platform pull request #22
Opened 2024-04-15 17:48 UTC by yujunliang

2024-04-17 19:02 UTC, Lawouach requested changes
Please adjust as per the comments.

Also:

* add a changelog entry
* add the signature to the commits as per the DCO

2024-04-17 19:02 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +# Copyright 2023 Google LLC.
Please consider removing. Unless this is mandatory on your side.

2024-04-17 19:02 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +from logzero import logger
This has been dropped in favour of directly using the `logging` module

```python
import logging
from typing import Any, Dict

```

Then:


```python
__all__ = ["set_instance_tags"]
logger = logging.getLogger("chaostoolkit")
```

2024-04-17 19:02 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +__all__ =["set_instance_tags"]
add missing space after `=`

2024-04-17 19:02 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +                              secrets: Secrets = None) -> Dict[str, Any]:
lint the signature

2024-04-17 19:02 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +
add missing docstring

2024-04-17 19:02 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +    wait_on_extended_operation(operation)
missing a return statement

2024-04-17 19:02 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +    client = compute_v1.InstancesClient()
Pass the credentials to the function

```python
client = compute_v1.InstancesClient(credentials=credentials)
```

2024-04-17 19:02 UTC, Lawouach commented on tests/test_compute.py
> +    settag_req.assert_called_with(instance=instance_name, project=project_id,zone=zone_name,tags_resource=tags(fingerprint=fixtures.compute.response_get["tags"]["fingerprint"],items=tags_list))
lint to a column size of 80 max

2024-04-23 16:02 UTC, Lawouach requested changes
Hi @yujunliang,

Thank you for the update.

It contains a few more linting errors https://github.com/chaostoolkit-incubator/chaostoolkit-google-cloud-platform/actions/runs/8803403285/job/24161698162

You can ignore the errors regarding building on MacOSX. I'll fix that once we have merged.

2024-04-24 12:23 UTC, yujunliang commented on chaosgcp/compute/actions.py
> +
Done

2024-04-29 16:42 UTC, Lawouach requested changes
a couple of changes

2024-04-29 16:42 UTC, Lawouach commented on chaosgcp/compute/actions.py
> +    wait_on_extended_operation(operation)
You are still missing that return statement :)

2024-04-29 16:42 UTC, Lawouach commented on tests/test_compute.py
> +Signed-off-by: Yujun Liang <yujunl@google.com>
I think that line is likely nor where it should. please remove

2024-04-29 16:57 UTC, yujunliang commented on tests/test_compute.py
> +Signed-off-by: Yujun Liang <yujunl@google.com>
Removed.

2024-04-29 17:23 UTC, merged